# Mapping of Label -> List of associated GitHub issues
KNOWN_ISSUES: dict[str, list[int]] = {
    "ABeautifulGame-glTF": [460],
    "AlphaBlendModeTest-glTF-Embedded": [454],
    "AlphaBlendModeTest-glTF": [453],
    "AlphaBlendModeTest-glTF-Binary": [453],
    "AnimatedCube-glTF": [457],
    "AnimatedMorphCube-glTF": [457],
    "AnimatedMorphCube-glTF-Binary": [457],
    "AnimatedMorphCube-glTF-Quantized": [455, 457],
    "AnimatedTriangle-glTF-Embedded": [452, 457],
    "AnimatedTriangle-glTF": [452, 457],
    "AnisotropyBarnLamp-glTF": [455],
    "AnisotropyBarnLamp-glTF-Binary": [455],
    "AnisotropyBarnLamp-glTF-KTX-BasisU": [455],
    "AnisotropyDiscTest-glTF": [455],
    "AnisotropyDiscTest-glTF-Binary": [455],
    "AnisotropyRotationTest-glTF": [455],
    "AnisotropyRotationTest-glTF-Binary": [455],
    "AnisotropyStrengthTest-glTF": [455, 471], # TODO: The spheres don't render properly
    "AnisotropyStrengthTest-glTF-Binary": [455, 471], # TODO: The spheres don't render properly
    "AntiqueCamera-glTF": [460],
    "AntiqueCamera-glTF-Binary": [460],
    "AttenuationTest-glTF": [455],
    "AttenuationTest-glTF-Binary": [455],
    "Avocado-glTF": [451],
    "Avocado-glTF-Binary": [451],
    "Avocado-glTF-Draco": [451, 455],
    "Avocado-glTF-Quantized": [451, 455],
    "BarramundiFish-glTF": [451],
    "BarramundiFish-glTF-Binary": [451],
    "BarramundiFish-glTF-Draco": [451, 455],
    "BoomBox-glTF": [451],
    "BoomBox-glTF-Binary": [451],
    "BoomBox-glTF-Draco": [451, 455],
    "BoomBoxWithAxes-glTF": [451],
    "Box-glTF-Embedded": None,
    "Box-glTF": None,
    "Box-glTF-Binary": None,
    "Box-glTF-Draco": [455],
    # "Box With Spaces-glTF": [] # TODO: Triage
    "BoxAnimated-glTF-Embedded": [457],
    "BoxAnimated-glTF": [457],
    "BoxAnimated-glTF-Binary": [457],
    "BoxInterleaved-glTF-Embedded": [472],
    "BoxInterleaved-glTF": [472],
    "BoxInterleaved-glTF-Binary": [472],
    "BoxTextured-glTF-Embedded": [454],
    "BoxTextured-glTF": None,
    "BoxTextured-glTF-Binary": None,
    "BoxTexturedNonPowerOfTwo-glTF-Embedded": [454],
    "BoxTexturedNonPowerOfTwo-glTF": None,
    "BoxTexturedNonPowerOfTwo-glTF-Binary": None,
    "BoxVertexColors-glTF-Embedded": [452],
    "BoxVertexColors-glTF": [452],
    "BoxVertexColors-glTF-Binary": [452],
    "BrainStem-glTF-Embedded": [457],
    "BrainStem-glTF": [457],
    "BrainStem-glTF-Binary": [457],
    "BrainStem-glTF-Draco": [455, 457],
    "Cameras-glTF-Embedded": [452],
    "Cameras-glTF": [452],
    "CarbonFibre-glTF": [455, 460, 461],
    "CarbonFibre-glTF-Binary": [455, 460, 461],
    "CesiumMan-glTF-Embedded": [454, 457],
    "CesiumMan-glTF": [457],
    "CesiumMan-glTF-Binary": [457],
    "CesiumMan-glTF-Draco": [455, 457],
    "CesiumMilkTruck-glTF-Embedded": [451, 454],
    "CesiumMilkTruck-glTF": [451],
    "CesiumMilkTruck-glTF-Binary": [451],
    "CesiumMilkTruck-glTF-Draco": [451, 455],
    # "ChairDamaskPurplegold-glTF": [], # TODO: Triage
    # "ChairDamaskPurplegold-glTF-Binary": [],  # TODO Triage
    "ClearCoatCarPaint-glTF": [455, 460],
    "ClearCoatCarPaint-glTF-Binary": [455, 460],
    "ClearCoatTest-glTF": [451, 455, 460], # TODO: Labels don't render properly
    "ClearCoatTest-glTF-Binary": [451, 455, 460], # TODO: Labels don't render properly
    "ClearcoatWicker-glTF": [455, 460, 461],
    "ClearcoatWicker-glTF-Binary": [455, 460, 461],
    "Corset-glTF": [451],
    "Corset-glTF-Binary": [451],
    "Corset-glTF-Draco": [451, 455],
    "Cube-glTF": None,
    "DamagedHelmet-glTF-Embedded": [454, 460, 461, 462],
    "DamagedHelmet-glTF": [460, 461, 462],
    "DamagedHelmet-glTF-Binary": [460, 461, 462],
    # TODO: DiffuseTransmissionPlant-glTF
    "DiffuseTransmissionTeacup-glTF": [455, 460, 461],
    "DiffuseTransmissionTeacup-glTF-Binary": [455, 460, 461],
    # TODO: DirectionalLight-glTF
    "DispersionTest-glTF": [455],
    "DispersionTest-glTF-Binary": [455],
    "DragonAttenuation-glTF": [455],
    "DragonAttenuation-glTF-Binary": [455],
    "DragonDispersion-glTF": [455],
    "DragonDispersion-glTF-Binary": [455],
    "Duck-glTF-Embedded": [454], # TODO Camera
    # TODO Duck-glTF Camera
    # TODO Duck-glTF-Binary Camera
    "Duck-glTF-Draco": [455],
    "Duck-glTF-Quantized": [455],
    "EmissiveStrengthTest-glTF": [455],
    "EmissiveStrengthTest-glTF-Binary": [455],
    # TODO "EnvironmentTest-glTF"
}
