name: Android build

on:
  pull_request:

# Cancel previous runs if a more recent commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  android-build:
    name: Check Android build with gradle
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Vulkan SDK
        run: |
          wget -q https://sdk.lunarg.com/sdk/download/1.4.313.0/linux/vulkansdk-linux-x86_64-1.4.313.0.tar.xz
          if ! echo "4e957b66ade85eeaee95932aa7e3b45aea64db373c58a5eaefc8228cc71445c2 vulkansdk-linux-x86_64-1.4.313.0.tar.xz" | sha256sum -c --status; then
            echo "Invalid SHA256 for VulkanSDK's binary. Aborting."
            exit 1
          fi
          mkdir "${HOME}/vulkan-sdk"
          tar -xf vulkansdk-linux-x86_64-1.4.313.0.tar.xz -C "${HOME}/vulkan-sdk"
          echo "VULKAN_SDK=${HOME}/vulkan-sdk/1.4.313.0/x86_64" >> $GITHUB_ENV
      - name: Build all projects
        run: |
          ./gradlew buildRelease -PENABLE_32BIT_ARM=true
